spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yourdb
    driver-class-name: org.postgresql.Driver
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: youremail@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
      protocol: smtp

application:
  security:
    admin:
      create:
        code: CallMeRevenge
    jwt:
      secret-key: your_secret_key
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    mailing:
      frontend:
        activation-url: http://localhost:3000/activation-code
        reset-url: http://localhost:3000/reset-code
    cors:
      origins: http://localhost:4200,http://localhost:8080,http://localhost:3000,http://localhost:5173

server:
  servlet:
    context-path: /api/v1
  port: 8000

springdoc:
  default-consumes-media-type: application/json

logging:
  level:
    org:
      springframework:
        security: DEBUG